import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React, { useEffect, useReducer, useRef } from "react";

const initialState = {
  activeMenu: "home", // Set the default active menu to 'home'
  menuOpen: false,
  scrollY: 0,
};

function reducer(state, action) {
  switch (action.type) {
    case "TOGGLE":
      return {
        ...state,
        activeMenu: state.activeMenu === action.payload ? "" : action.payload,
        menuOpen: !state.menuOpen,
      };
    case "setScrollY":
      return { ...state, scrollY: action.payload };
    case "setActiveMenu":
      return { ...state, activeMenu: action.payload };
    default:
      return state;
  }
}

function Header1() {
  const [state, dispatch] = useReducer(reducer, initialState);
  const headerRef = useRef(null);
  const { pathname } = useRouter();

  const handleScroll = () => {
    dispatch({ type: "setScrollY", payload: window.scrollY });
  };

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  useEffect(() => {
    // Set the active menu based on the current pathname
    if (pathname === "/") {
      dispatch({ type: "setActiveMenu", payload: "home" });
    } else if (pathname.startsWith("/category")) {
      dispatch({ type: "setActiveMenu", payload: "job-category" });
    }else if (pathname.startsWith("/job-listing1")) {
      dispatch({ type: "setActiveMenu", payload: "job-category" });
    }else if (pathname.startsWith("/job-details")) {
      dispatch({ type: "setActiveMenu", payload: "job-category" });
    } else if (pathname.startsWith("/candidates-dashboard")) {
      dispatch({ type: "setActiveMenu", payload: "pages" });
    } else if (pathname.startsWith("/company")) {
      dispatch({ type: "setActiveMenu", payload: "company" });
    } else if (pathname.startsWith("/blog-grid")) {
      dispatch({ type: "setActiveMenu", payload: "blog" });
    } else if (pathname === "/contact") {
      dispatch({ type: "setActiveMenu", payload: "contact" });
    } else {
      dispatch({ type: "setActiveMenu", payload: "" });
    }

    const burger = document.querySelector(".mobile-menu-btn");
    const nav = document.querySelector(".main-menu");
    const menuClose = document.querySelector(".menu-close-btn");

    if (burger && nav && menuClose) {
      burger.addEventListener("click", () => {
        nav.classList.add("show-menu");
      });

      menuClose.addEventListener("click", () => {
        nav.classList.remove("show-menu");
      });
    }

    return () => {
      if (burger && menuClose) {
        burger.removeEventListener("click", () => {});
        menuClose.removeEventListener("click", () => {});
      }
    };
  }, [pathname]);

  const handleMenu = (menuName) => {
    dispatch({ type: "TOGGLE", payload: menuName });
  };

  return (
    <>
      <Head>
        <title>JOBES- Job Portal NextJs Template</title>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/images/sm-logo.svg" type="image/gif" sizes="20x20" />
      </Head>
      <header
        ref={headerRef}
        className={state.scrollY > 120 ? "header-area style-1 sticky" : "header-area style-1"}
      >
        <div className="header-main-logo d-lg-block d-none">
          <Link href="/" legacyBehavior>
            <a>
              <img alt="image" src="assets/images/header1-logo.svg" />
            </a>
          </Link>
        </div>
        <div className="menu-topbar-area">
          <div className="top-bar">
            <p>
              Welcome to Our Job Portal!{" "}
              <Link href="/candidates-dashboard/bookmark" legacyBehavior>
                <a>Save Jobs</a>
              </Link>
            </p>
            <div className="top-bar-right">
              <div className="language-select">
                <img src="assets/images/icon/flag-eng.svg" alt="image" />
                <span>Language</span>
                <ul className="topbar-sublist">
                  <li>
                    <img src="assets/images/icon/flag-germeny.svg" alt="image" />
                    <span>Germany</span>
                  </li>
                  <li>
                    <img src="assets/images/icon/flag-french.svg" alt="image" />
                    <span>French</span>
                  </li>
                  <li>
                    <img src="assets/images/icon/flag-bangla.svg" alt="image" />
                    <span>Bengali</span>
                  </li>
                </ul>
              </div>
              <div className="social-area">
                <ul>
                  <li>
                    <a href="https://www.facebook.com/">
                      <i className="bx bxl-facebook" />
                    </a>
                  </li>
                  <li>
                    <a href="https://twitter.com/">
                      <i className="bx bxl-twitter" />
                    </a>
                  </li>
                  <li>
                    <a href="https://www.linkedin.com/">
                      <i className="bx bxl-linkedin" />
                    </a>
                  </li>
                  <li>
                    <a href="https://www.instagram.com/">
                      <i className="bx bxl-instagram" />
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <div className="menu-area">
            <div className="header-logo">
              <Link href="/" legacyBehavior>
                <a>
                  <img alt="image" className="img-fluid" src="assets/images/header1-logo.svg" />
                </a>
              </Link>
            </div>
            <div className="main-menu">
              <div className="mobile-logo-area d-lg-none d-flex justify-content-between align-items-center">
                <div className="mobile-logo-wrap">
                  <Link href="/" legacyBehavior>
                    <a>
                      <img alt="image" src="assets/images/header1-logo.svg" />
                    </a>
                  </Link>
                </div>
                <div className="menu-close-btn">
                  <i className="bi bi-x-lg" />
                </div>
              </div>
              <ul className="menu-list">
                <li
                  className={state.activeMenu === "home" ? "menu-item active" : "menu-item"}
                >
                  <Link href="/" legacyBehavior>
                    <a>Home</a>
                  </Link>
                </li>
                <li
                  className={state.activeMenu === "job-category" ? "menu-item menu-item-has-children active" : "menu-item menu-item-has-children"}
                >
                  <Link href="#" legacyBehavior>
                    <a>Find Jobs</a>
                  </Link>
                  <i
                    className="bi bi-plus dropdown-icon"
                    onClick={() => handleMenu("job-category")}
                  />
                  <ul className={state.activeMenu === "job-category" ? "sub-menu d-block" : "sub-menu"}>
                    <li>
                      <Link href="/category" legacyBehavior>
                        <a>Job Category</a>
                      </Link>
                    </li>
                    <li>
                      <Link href="/job-listing1" legacyBehavior>
                        <a>Job Listing</a>
                      </Link>
                    </li>
                    <li>
                      <Link href="/job-details" legacyBehavior>
                        <a>Job Details</a>
                      </Link>
                    </li>
                  </ul>
                </li>
                <li
                  className={state.activeMenu === "pages" ? "menu-item menu-item-has-children active" : "menu-item menu-item-has-children"}
                >
                  <Link href="#" legacyBehavior>
                    <a>Pages</a>
                  </Link>
                  <i
                    className="bi bi-plus dropdown-icon"
                    onClick={() => handleMenu("pages")}
                  />
                  <ul className={state.activeMenu === "pages" ? "sub-menu d-block" : "sub-menu"}>
                    <li>
                      <Link href="/candidates-dashboard/dashboard" legacyBehavior>
                        <a>Candidate Dashboard</a>
                      </Link>
                    </li>
                    <li>
                      <Link href="/job-post" legacyBehavior>
                        <a>Post A Job</a>
                      </Link>
                    </li>
                    <li>
                      <Link href="/pricing-plan" legacyBehavior>
                        <a>Pricing Plan</a>
                      </Link>
                    </li>
                    <li>
                      <Link href="/faq" legacyBehavior>
                        <a>FAQ</a>
                      </Link>
                    </li>
                    <li>
                      <Link href="/error" legacyBehavior>
                        <a>Error</a>
                      </Link>
                    </li>
                    <li>
                      <Link href="/login" legacyBehavior>
                        <a>Login</a>
                      </Link>
                    </li>
                    <li>
                      <Link href="/register" legacyBehavior>
                        <a>Register</a>
                      </Link>
                    </li>
                  </ul>
                </li>
                <li
                  className={state.activeMenu === "company" ? "menu-item menu-item-has-children active" : "menu-item menu-item-has-children"}
                >
                  <Link href="#" legacyBehavior>
                    <a>Employers</a>
                  </Link>
                  <i
                    className="bi bi-plus dropdown-icon"
                    onClick={() => handleMenu("company")}
                  />
                  <ul className={state.activeMenu === "company" ? "sub-menu d-block" : "sub-menu"}>
                    <li>
                      <Link href="/company-listing1" legacyBehavior>
                        <a>Company Listing</a>
                      </Link>
                    </li>
                    <li>
                      <Link href="/company-details" legacyBehavior>
                        <a>Company Details</a>
                      </Link>
                    </li>
                    <li>
                      <Link href="/company/company-dashboard" legacyBehavior>
                        <a>Company Dashboard</a>
                      </Link>
                    </li>
                  </ul>
                </li>
                <li
                  className={state.activeMenu === "blog" ? "menu-item menu-item-has-children active" : "menu-item menu-item-has-children"}
                >
                  <Link href="/blog-grid" legacyBehavior>
                    <a>Blog</a>
                  </Link>
                  <i
                    className="bi bi-plus dropdown-icon"
                    onClick={() => handleMenu("blog")}
                  />
                </li>
                <li
                  className={state.activeMenu === "contact" ? "menu-item active" : "menu-item"}
                >
                  <Link href="/contact" legacyBehavior>
                    <a>Contact</a>
                  </Link>
                </li>
              </ul>
            </div>
            <div className="header-action">
              <Link href="/login" legacyBehavior>
                <a className="btn btn-primary">Login</a>
              </Link>
              <Link href="/register" legacyBehavior>
                <a className="btn btn-primary">Register</a>
              </Link>
            </div>
          </div>
        </div>
        <div className="mobile-menu-btn">
          <i className="bi bi-list" />
        </div>
      </header>
    </>
  );
}

export default Header1;
